### ISSUE TITLE
ERROR:main:请求失败：403 Client Error: Forbidden for url: https://api.aliyundrive.com/adrive/v4/batch

### ISSUE THREAD

**Issue by yichengnanfeng** [shihuibei/aliyun_copy#1]
这个问题怎么解决，用项目里面默认的分享链接可以，我自己找的分享链接不行，链接如下：
https://www.aliyundrive.com/s/8HKyr7EgMRK

详细报错信息：
$ python zhuancun.py
INFO:__main__:分享名称: CCTV 大型栏目：自然传奇、人与自然、动物世界合集【2014-2023 高清】
INFO:__main__:文件数量: 1
ERROR:__main__:请求失败：403 Client Error: Forbidden for url: https://api.aliyundrive.com/adrive/v4/batch
ERROR:__main__:直接转存目录时发生异常: 403 Client Error: Forbidden for url: https://api.aliyundrive.com/adrive/v4/batch
INFO:__main__:开始执行逐个转存...
ERROR:__main__:请求失败：400 Client Error: Bad Request for url: https://api.aliyundrive.com/adrive/v2/file/list_by_share
ERROR:__main__:请求失败：400 Client Error: Bad Request for url: https://api.aliyundrive.com/adrive/v2/file/list_by_share
ERROR:__main__:An error occurred: 400 Client Error: Bad Request for url: https://api.aliyundrive.com/adrive/v2/file/list_by_share
{'parent_file_id': 'root', 'type': 'folder', 'file_id': '6738460e3e56a4ce66e14489a33fd45c76f724fc', 'domain_id': 'bj29', 'drive_id': 'XXXXXXXX', 'file_name': 'CCTV 大型栏目：自然传奇、人与自然、动物世界合集【2014-2023 高清】', 'encrypt_mode': '', 'status': 'available', 'exist': True}

**Comment by yichengnanfeng** [comment]
我更新了下share_token之后莫名其妙又可以了，好像是share_token有效期比较短，或者是刷新了页面share_token重置了

**Comment by shihuibei** [comment]
嗯，这种一般是鉴权的凭证失效才会出现报错，参数什么的目前使用应该是不缺少的。
